name: diffuser
channels:
- defaults
- conda-forge
dependencies:
- python=3.8
- setuptools==63.2.0
- wheel==0.38.4
- pip==22.2.2
- patchelf 
- cmake
- pip:
    # Split into groups, with mujoco dependencies first
    - wheel  # explicitly include wheel here too
    - numpy
    - cython
    - mujoco-py==2.0.2.13
    # Then install torch
    - -f https://download.pytorch.org/whl/torch_stable.html
    - torch==1.9.1+cu111
    # Then the rest
    - gym==0.18.0
    - matplotlib==3.3.4
    - typed-argument-parser
    - scikit-image==0.17.2
    - scikit-video==1.1.11
    - gitpython
    - einops
    - ffmpeg
    - ffprobe
    - pillow==7.2.0
    - tqdm
    - pandas
    - wandb
    - flax>=0.3.5
    - jax<=0.2.21
    - ray==2.0.0
    - crcmod
    - google-api-python-client
    - cryptography
    - gdown>=4.6.0
    - git+https://github.com/JannerM/doodad.git@janner
    - git+https://github.com/Farama-Foundation/d4rl@f2a05c0d66722499bf8031b094d9af3aea7c372b#egg=d4rl
